Null merge commit ancestor bug fix
spgroup/miningframework pull request #130
Opened 2021-04-15 00:17 UTC by leonardoAnjos16

The tool may launch `NullPointerException` when trying to perform some action with a given `MergeCommit` that has `null` for its `ancestor` field.

This PR fixes that by ignoring merge commits for which `git merge-base` can't compute its parents' common ancestor.

2021-04-27 00:11 UTC, pauloborba requested changes

2021-04-27 00:11 UTC, pauloborba commented on src/main/project/Project.groovy
> +                    println "Skipping merge commit ${SHA}"
@leonardoAnjos16 esse tipo de informação, de cenários descartados, não é colocada em nenhuma planilha? ou log?

2021-04-27 00:11 UTC, pauloborba commented on src/main/project/Project.groovy
> +        String actualOutput = gitMergeBase.getText().trim()
@leonardoAnjos16 tem que alterar as outras chamadas a esse método, senão vai quebrar as outras instanciações do framework

2021-04-27 12:52 UTC, rafaelmotaalves approved these changes

2021-04-27 20:11 UTC, leonardoAnjos16 commented on src/main/project/Project.groovy
> +                    println "Skipping merge commit ${SHA}"
Vou fazer isso!

2021-04-27 20:12 UTC, leonardoAnjos16 commented on src/main/project/Project.groovy
> +        String actualOutput = gitMergeBase.getText().trim()
Certo, vou ajeitar isso também!

2021-04-28 23:35 UTC, leonardoAnjos16 commented on src/main/project/Project.groovy
> +        String actualOutput = gitMergeBase.getText().trim()
@pauloborba O senhor se refere a que método, professor? 🤔
O `getCommonAncestor` só é chamado em `getMergeCommits` e o `constructAndRunGitMergeBase` só é chamado em `getCommonAncestor`

2021-04-29 14:22 UTC, pauloborba commented on src/main/project/Project.groovy
> +        String actualOutput = gitMergeBase.getText().trim()
@leonardoAnjos16 me refiro ao getCommonAncestor. ele não é chamado em outras partes do framework que não estão relacionadas aos serviços do seu estudo?

2021-04-29 20:27 UTC, leonardoAnjos16 commented on src/main/project/Project.groovy
> +        String actualOutput = gitMergeBase.getText().trim()
@pauloborba isso, ele só é chamado no método `getMergeCommits` dessa própria classe mesmo

2021-04-29 20:56 UTC, pauloborba commented on src/main/project/Project.groovy
> +        String actualOutput = gitMergeBase.getText().trim()
@leonardoAnjos16 certo, e a interface de getMergeCommits foi mantida exceto pelo que ele escreve no log, né? ou seja ele não retorna uma nova exceção, etc. e assim não afeta quem chama ele, correto?

2021-04-29 20:58 UTC, leonardoAnjos16 commented on src/main/project/Project.groovy
> +        String actualOutput = gitMergeBase.getText().trim()
@pauloborba exato!

2021-04-29 21:00 UTC, leonardoAnjos16 commented on src/main/project/Project.groovy
> +                    println "Skipping merge commit ${SHA}"
@pauloborba pensei em criar uma planilha a parte pra listar os pares (projeto, merge commit) que foram descartados. O senhor acha uma boa ideia?

2021-04-29 21:02 UTC, pauloborba commented
***@***.***Anjos16, boa
On 29 Apr 2021 18:00 -0300, Leonardo dos Anjos Silva ***@***.***>, wrote:
> @leonardoAnjos16 commented on this pull request.
> In src/main/project/Project.groovy:
> >
> +                try {
> +                    String ancestorSHA = getCommonAncestor(SHA, parentsSHA)
> +                    MergeCommit mergeCommit = new MergeCommit(SHA, parentsSHA, ancestorSHA)
> +                    mergeCommits.add(mergeCommit)
> +                } catch (UnexpectedOutputException e) {
> +                    println "Skipping merge commit ${SHA}"
> @pauloborba pensei em criar uma planilha a parte pra listar os pares (projeto, merge commit) que foram descartados. O senhor acha uma boa ideia?
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub, or unsubscribe.

2021-05-05 18:34 UTC, galilasmb approved these changes

2021-05-06 17:05 UTC, leusonmario approved these changes

2021-06-01 20:53 UTC, merged