Extend the CSDiff study to any set of separators and any file extension
spgroup/miningframework pull request #142
Opened 2021-11-01 01:31 UTC by heitorado

- Add new version of CSDiff script that can handle any file extension and any number of syntactic separators
- Modify the original CSDiff study that worked only with java files to work with any file extension
- Add two new miningframework parameters
  - `-e`: to specify the file extension (e.g. `.rb`, `.ts`)
  - `-l`: to specify the set of separators (e.g. `'{ } [ ] < > ;'`
  
For instance, given a `.csv` file named `typescript_projects.csv` with the following content:
|path|name|
|-|-|
|https://github.com/DefinitelyTyped/DefinitelyTyped|DefinitelyTyped|
|https://github.com/microsoft/vscode|vscode|
|https://github.com/microsoft/TypeScript|TypeScript|
|https://github.com/storybookjs/storybook|storybook|
|https://github.com/n8n-io/n8n|n8n|

A TypeScript-focused CSDiff study could be run in the five repositories like this:
`./gradlew run --args="-e .ts -l '( ) [ ] , ; { } < > | : ??' -i injectors.CSDiffModule -t 5 -s 01/01/2020 -u 31/10/2021 ./typescript_projects.csv ./TypeScriptResults"`

2021-11-04 12:54 UTC, pauloborba requested changes

2021-11-04 12:54 UTC, pauloborba commented on src/main/arguments/ArgsParser.groovy
> +        this.cli.e(longOpt: 'extension', args: 1, argName: 'file extenson', 'Specify the file extension that should be used in the analysis (e.g. .rb, .ts, .java, .cpp. Default: .java)')
@heitorado podes adicionar documentação informando que essas opções só são válidas para estudos com o CSDIFF? talvez precise ajustar algo no README também

2021-11-04 17:22 UTC, leonardoAnjos16 commented on src/main/services/dataCollectors/csDiffCollector/CSDiffRunner.groovy
> +        String diff3PathFileName = getOutputPath(baseFile.getParent(), "diff3").toString()
@heitorado pra que servem essas variáveis? Pelo que eu vi, o `csdiff_v2.sh` salva os resultados dos **merges** em arquivos com nomes já predefinidos, certo?

2021-11-04 17:27 UTC, leonardoAnjos16 commented on src/main/services/dataCollectors/csDiffCollector/CSDiffRunner.groovy
> +        String diff3PathFileName = getOutputPath(baseFile.getParent(), "diff3").toString()
@heitorado pra que servem essas variáveis? Pelo que eu vi, `o csdiff_v2.sh` salva os resultados dos **merges** em arquivos com nomes já predefinidos, certo?

2021-11-05 14:50 UTC, heitorado commented on src/main/services/dataCollectors/csDiffCollector/CSDiffRunner.groovy
> +        String diff3PathFileName = getOutputPath(baseFile.getParent(), "diff3").toString()
Ah! Tens razão, Leonardo. São _leftovers_ de testes que eu tava fazendo. Vou remover.

2021-11-17 18:48 UTC, pauloborba approved these changes

2021-11-17 18:49 UTC, merged