Save log console in txt file and run all analysis
spgroup/miningframework pull request #146
Opened 2022-08-23 14:47 UTC by galilasmb

- Save console log in a txt file
- Add all analysis

2022-08-23 18:07 UTC, barbosamaatheus approved these changes

2022-08-23 21:39 UTC, pauloborba requested changes

2022-08-23 21:39 UTC, pauloborba commented on src/main/services/outputProcessors/soot/Main.groovy
> +        FileOutputStream file = new FileOutputStream("outConsole.txt");
@galilasmb não seria importante tratar as possíveis exceções?

2022-08-23 21:39 UTC, pauloborba commented on src/main/services/outputProcessors/soot/Main.groovy
> +public class TeePrintStream extends PrintStream {
@galilasmb essa classe não já existe em outros pacotes?

2022-08-23 21:39 UTC, pauloborba commented on src/main/services/outputProcessors/soot/RunSootAnalysisOutputProcessor.groovy
> +//            resultStringBuilder.append(";${algorithm.generateHeaderName()};time (s)");
@galilasmb por que não remover?

2022-08-25 11:49 UTC, galilasmb commented on src/main/services/outputProcessors/soot/Main.groovy
> +        FileOutputStream file = new FileOutputStream("outConsole.txt");
Seria sim, foi erro meu. Corrigir.

2022-08-25 11:50 UTC, galilasmb commented on src/main/services/outputProcessors/soot/Main.groovy
> +public class TeePrintStream extends PrintStream {
Não, é uma classe nova, específica pra salvar arquivos.

2022-08-25 11:50 UTC, galilasmb commented on src/main/services/outputProcessors/soot/RunSootAnalysisOutputProcessor.groovy
> +//            resultStringBuilder.append(";${algorithm.generateHeaderName()};time (s)");
Combinado.

2022-08-26 16:44 UTC, barbosamaatheus approved these changes

2022-08-30 12:10 UTC, galilasmb commented on src/main/services/outputProcessors/soot/Main.groovy
>              e.printStackTrace();
Não parar a execução caso aconteça algum erro de salvar o log.

2022-09-06 13:03 UTC, pauloborba approved these changes

2022-09-09 12:17 UTC, barbosamaatheus approved these changes

2022-09-13 12:03 UTC, merged