Script for execution 10 times
spgroup/miningframework pull request #171
Opened 2023-04-26 14:13 UTC by galilasmb

2023-04-26 14:17 UTC, barbosamaatheus submitted a review, later dismissed

2023-04-27 12:40 UTC, pauloborba requested changes

2023-04-27 12:40 UTC, pauloborba commented on scripts/run_experiment.sh
> +
pessoal, depois do loop a gente precisaria de um outro para coletar as medições de tempo de cada execução e fazer as análises e gráficos em cima disso

podia fazer o double check também se os resultados FP e FN de todas as execuções foram os mesmos também

2023-04-27 16:18 UTC, galilasmb commented on scripts/run_experiment.sh
> +
Fiz um commit com estes scripts, agora está de acordo.

2023-04-27 18:24 UTC, barbosamaatheus approved these changes

2023-05-17 13:13 UTC, pauloborba requested changes

2023-05-17 13:13 UTC, pauloborba commented on scripts/generate_analysis_results.py
@galilasmb isso deveria também estar no diretório específico de análise estática, não?

2023-05-26 12:56 UTC, barbosamaatheus approved these changes

2023-06-12 13:47 UTC, galilasmb commented on results-with-build-information.csv
> +MPAndroidChart;9531ba69895cd64fce48038ffd8df2543eeea1d2;com.github.mikephil.charting.renderer.LineChartRenderer;drawData(Canvas);[76, 77, 78];true;[];[76, 78];[];
As modificações dos cenários com conflitos textuais.

2023-06-12 14:48 UTC, pauloborba requested changes

2023-06-12 14:48 UTC, pauloborba commented on input/LOI.csv
> +druid;05168808c278c080c59c19e858d9471b316cd1f5;com.metamx.druid.loading.S3SegmentPusher;"push(File; DataSegment)";Roberto;No
@galilasmb verifica as aspas, o padrão, etc. para deixar uniforme

2023-06-12 14:48 UTC, pauloborba commented on scripts/generate_analysis_results.py
@galilasmb verificar diretório

2023-06-15 17:18 UTC, barbosamaatheus approved these changes

2023-06-15 18:17 UTC, pauloborba approved these changes

2023-06-15 18:18 UTC, merged