Updating .jar
spgroup/miningframework pull request #174
Opened 2023-06-16 20:25 UTC by galilasmb

2023-06-16 20:46 UTC, pauloborba requested changes

2023-06-16 20:46 UTC, pauloborba commented on dependencies/soot-analysis-0.2.1-SNAPSHOT-jar-with-dependencies.jar
@galilasmb isso é um JAR definitivo? se não for, a gente não deveria estar atualizando o master do repo remoto

2023-06-19 23:29 UTC, galilasmb commented on dependencies/soot-analysis-0.2.1-SNAPSHOT-jar-with-dependencies.jar
Ainda é pra teste, coloquei aqui pra gerar o docker a partir da nossa branch. Não precisa atualizar a master.

2023-07-24 19:10 UTC, barbosamaatheus requested changes

2023-07-24 19:10 UTC, barbosamaatheus commented on input/LOI.csv
> +antlr4;69ff2669eec265e25721dbc27cb00f6c381d0b41;org.antlr.v4.codegen.target.Python2Target;python2Keywords;Leuson;-
removeu LOI?

2023-07-24 20:16 UTC, pauloborba requested changes

2023-07-24 20:16 UTC, pauloborba commented on scripts/experiment_static_analysis/generate_conflicts_csv_from_logs.py
> +#!/usr/bin/python
comentário?

2023-07-25 00:17 UTC, galilasmb commented on input/LOI.csv
> +antlr4;69ff2669eec265e25721dbc27cb00f6c381d0b41;org.antlr.v4.codegen.target.Python2Target;python2Keywords;Leuson;-
Sim, deixei somente os 99 cenários que selecionamos.

2023-07-25 11:50 UTC, barbosamaatheus commented on input/LOI.csv
> +antlr4;69ff2669eec265e25721dbc27cb00f6c381d0b41;org.antlr.v4.codegen.target.Python2Target;python2Keywords;Leuson;-
Tu fez a remoção dos demais cenários por aqui? achei q tinha excluido do results-with-build-information.

2023-07-25 12:33 UTC, galilasmb commented on input/LOI.csv
> +antlr4;69ff2669eec265e25721dbc27cb00f6c381d0b41;org.antlr.v4.codegen.target.Python2Target;python2Keywords;Leuson;-
Excluí dos dois, coloquei um - nos que não vamos usar, assim facilita o filtro.

2023-07-25 12:48 UTC, barbosamaatheus approved these changes

2023-07-25 13:25 UTC, pauloborba approved these changes

2023-07-25 13:27 UTC, merged