Updating scripts to run all analyses
spgroup/miningframework pull request #176
Opened 2023-09-20 13:07 UTC by galilasmb

2024-05-02 16:34 UTC, barbosamaatheus requested changes

2024-05-02 16:34 UTC, barbosamaatheus commented on src/main/services/outputProcessors/soot/README.md
> + -printDepthSVFA                         Print depth in SVFA analysis
Deveria adicionar o deeplimit aqui também, não?

2024-05-02 19:13 UTC, galilasmb commented on src/main/services/outputProcessors/soot/README.md
> + -printDepthSVFA                         Print depth in SVFA analysis
Boa, verdade, feito!

2024-05-02 19:14 UTC, barbosamaatheus approved these changes

2024-05-02 19:21 UTC, Vinicius-resende-cin approved these changes

2024-05-02 20:04 UTC, pauloborba requested changes

2024-05-02 20:08 UTC, galilasmb commented on scripts/run_experiment.sh
Verdade, talvez alterar o nome para run_static_analyses_experiment

2024-05-07 12:26 UTC, pauloborba commented on scripts/run_experiment.sh
@galilasmb altera logo para facilitar a revisão

2024-05-07 17:39 UTC, pauloborba approved these changes

2024-05-07 17:39 UTC, merged