Removing numexp
spgroup/miningframework pull request #189
Opened 2024-05-21 14:30 UTC by galilasmb

There is an error during the experiment execution

2024-05-21 14:56 UTC, pauloborba requested changes

2024-05-21 14:56 UTC, pauloborba commented on requirements.txt
>  urllib3==1.26.18
@galilasmb isso não é usado por outras partes do projeto?

2024-05-21 14:56 UTC, pauloborba commented on requirements.txt
>  urllib3==1.26.18
digo, do framework e suas instanciações?

2024-05-21 15:11 UTC, galilasmb commented on requirements.txt
>  urllib3==1.26.18
Não, eu que inseri porque estava dando erro localmente, mas no servidor executou normalmente.

2024-05-21 15:13 UTC, galilasmb commented on requirements.txt
>  urllib3==1.26.18
Adicionei essa semana, nesse commit: https://github.com/spgroup/miningframework/commit/910ece0781e5ef42861e03def92a23222bc7bc3e

2024-05-21 20:33 UTC, pauloborba commented on requirements.txt
>  urllib3==1.26.18
que esquisito. continua dando erro localmente?

2024-05-22 17:58 UTC, Vinicius-resende-cin approved these changes

2024-05-22 23:16 UTC, pauloborba requested changes

2024-05-22 23:16 UTC, pauloborba commented on requirements.txt
>  urllib3==1.26.18
@galilasmb

2024-05-23 14:38 UTC, galilasmb commented on requirements.txt
>  urllib3==1.26.18
Não continua, tá funcionando normalmente agora, era erro no meu python

2024-05-23 17:50 UTC, pauloborba approved these changes

2024-05-23 17:50 UTC, merged