Add Docker image configuration
spgroup/miningframework pull request #190
Opened 2024-05-25 02:47 UTC by jpedroh

This PR adds a Dockerfile for easier execution of Mining Framework with Docker. The Docker image is based on [OpenJDK](https://hub.docker.com/_/openjdk) and exposes the compiled asset - built using installDist gradle task.

It also adds a CI job to build and push the image into the GitHub Container Registry. With the current configuration, the most recent commit in master will have an image available under: `ghcr.io/spgroup/miningframework:master`. Documentation on how to execute Mining Framework using the provided Docker image was also added to the README.

2024-05-29 14:28 UTC, jpedroh commented on Dockerfile
> +WORKDIR /usr/src/miningframework
This is just so we start with a clean sheet image instead of packaging all stuff that was used to build mining framework

2024-05-29 14:30 UTC, jpedroh commented on README.md
> +docker run -v $PWD/output:/usr/local/bin/miningframework/output/ -v $PWD/projects.csv:/usr/local/bin/miningframework/projects.csv --rm ghcr.io/spgroup/miningframework:master projects.csv
The behavior is the same as with Docker volumes. What's on the right of the `:` points to the path inside the container, thus using unix paths. What's on the left of the `:`is where the volume will be mapped in the host machine, i.e., where the files will be placed.

tbh, i've never used docker in non-unix OSes but I believe the volumes mapping certainky works similar as well.

2024-05-29 14:31 UTC, jpedroh commented on README.md
> +docker run -v $PWD/output:/usr/local/bin/miningframework/output/ -v $PWD/projects.csv:/usr/local/bin/miningframework/projects.csv --rm ghcr.io/spgroup/miningframework:master projects.csv
Esse erro é porque essas modificações ainda não estão na master, então essa tag da imagem ainda não existe. Tenta rodar o comando substituindo o `ghcr.io/spgroup/miningframework:master` por `ghcr.io/jpedroh/miningframework:feat-add-docker`

2024-05-29 16:34 UTC, Vinicius-resende-cin commented on README.md
> +docker run -v $PWD/output:/usr/local/bin/miningframework/output/ -v $PWD/projects.csv:/usr/local/bin/miningframework/projects.csv --rm ghcr.io/spgroup/miningframework:master projects.csv
Quando executo com essa substituição o erro muda:
```
./docker-entrypoint.sh: line 8: groupadd: command not found
./docker-entrypoint.sh: line 9: useradd: command not found
chown: invalid user: ‘user:group’
./docker-entrypoint.sh: line 16: exec: su-exec: not found
```

2024-05-29 21:28 UTC, jpedroh commented on README.md
> +docker run -v $PWD/output:/usr/local/bin/miningframework/output/ -v $PWD/projects.csv:/usr/local/bin/miningframework/projects.csv --rm ghcr.io/spgroup/miningframework:master projects.csv
Consegues tentar de novo usando o comando atualizado no readme? tinha umas mudanças que fiz que acabaram quebrando o entrypoint.

2024-05-29 23:10 UTC, Vinicius-resende-cin commented on README.md
> +docker run -v $PWD/output:/usr/local/bin/miningframework/output/ -v $PWD/projects.csv:/usr/local/bin/miningframework/projects.csv --rm ghcr.io/spgroup/miningframework:master projects.csv
O erro ainda acontece, parece que por conta da imagem do amazoncorretto não possuir esses comandos por default.
Quando adiciono a linha `RUN yum -y install shadow-utils.x86_64` no Dockerfile a imagem roda normalmente.

2024-05-29 23:15 UTC, jpedroh commented on README.md
> +docker run -v $PWD/output:/usr/local/bin/miningframework/output/ -v $PWD/projects.csv:/usr/local/bin/miningframework/projects.csv --rm ghcr.io/spgroup/miningframework:master projects.csv
Eu removi o entrypoint da imagem porque a corretto já tem as permissões dos arquivos funcionando corretamente, que era o motivo de eu estar usando o entrypoint antes.

Testa com a versão maia recente da imagem, talvez precise fazer pull da imagem usando o docker pull novamente.

2024-05-29 23:31 UTC, Vinicius-resende-cin commented on README.md
> +docker run -v $PWD/output:/usr/local/bin/miningframework/output/ -v $PWD/projects.csv:/usr/local/bin/miningframework/projects.csv --rm ghcr.io/spgroup/miningframework:master projects.csv
Fiz um pull da imagem e funcionou.

2024-05-30 19:19 UTC, Vinicius-resende-cin approved these changes

2024-05-30 20:57 UTC, pauloborba submitted a review, later dismissed

2024-06-05 19:19 UTC, galilasmb requested changes

2024-06-05 19:19 UTC, galilasmb commented on .github/workflows/build.yaml
> +    runs-on: ubuntu-latest
Cuidado com isso, é bom especificar a versão do ubuntu, já tivemos problemas com isso, usamos FROM ubuntu:22.04

2024-06-05 22:48 UTC, jpedroh commented on .github/workflows/build.yaml
> +    runs-on: ubuntu-latest
Boa, fixei na versão 22.04 ;)

2024-06-07 12:18 UTC, barbosamaatheus approved these changes

2024-06-11 18:15 UTC, pauloborba approved these changes

2024-06-11 18:15 UTC, merged